from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "Document",
    "FedRAGAnalyzer",
    "build_dashboard_fomc_payload",
    "build_dashboard_fomc_history_payload",
    "build_cpi_bias_history",
    "build_dashboard_cpi_payload",
    "build_cpi_knowledge_graph_payload",
    "BLSCPIClient",
    "CPISeriesDefinition",
    "CPIObservation",
    "CPIStore",
    "CPIIngestionService",
    "CPIIngestionError",
    "export_dashboard_cpi_js",
    "export_dashboard_kg_js",
    "build_dashboard_labor_payload",
    "build_labor_bias_history",
    "build_labor_knowledge_graph_payload",
    "BLSLaborClient",
    "LaborSeriesDefinition",
    "LaborObservation",
    "LaborStore",
    "LaborIngestionService",
    "LaborIngestionError",
    "export_dashboard_labor_js",
    "export_dashboard_labor_kg_js",
    "TreasuryParYieldClient",
    "build_treasury_slope_history",
    "treasury_slope_bias",
    "TreasuryPoint",
    "TreasuryStore",
    "TreasuryIngestionService",
    "TreasuryIngestionError",
    "build_treasury_dashboard_payload",
    "build_treasury_knowledge_graph_payload",
    "export_dashboard_treasury_js",
    "NyFedReferenceRateClient",
    "PolicyRatePoint",
    "PolicyRateStore",
    "PolicyRateIngestionService",
    "PolicyRateIngestionError",
    "policy_rate_bias",
    "build_policy_rate_bias_history",
    "build_dashboard_policy_rates_payload",
    "build_policy_rate_knowledge_graph_payload",
    "export_dashboard_policy_rates_js",
    "TreasuryRealYieldClient",
    "RealYieldPoint",
    "RealYieldStore",
    "BreakevenIngestionService",
    "BreakevenIngestionError",
    "breakeven_bias",
    "build_breakeven_series",
    "build_breakeven_bias_history",
    "build_dashboard_breakeven_payload",
    "build_breakeven_knowledge_graph_payload",
    "export_dashboard_breakeven_js",
    "FOMCIngestionService",
    "FOMCStatement",
    "FOMCStatementStore",
    "export_dashboard_fomc_js",
    "export_dashboard_fomc_history_js",
    "GraphChunk",
    "GraphEdge",
    "GraphNode",
    "KnowledgeGraph",
    "KnowledgeGraphBuilder",
    "KalshiEventClient",
    "KalshiMarketClient",
    "MarketIngestionService",
    "MarketOutcome",
    "MarketSnapshot",
    "MarketSnapshotStore",
    "MarketWatchConfig",
    "PolymarketEventClient",
    "PolymarketMarketClient",
    "build_dashboard_market_payload",
    "export_dashboard_market_js",
    "load_watchlist",
    "parse_calendar_statement_urls",
    "parse_statement_html",
    "snapshot_to_document",
]

_EXPORTS: dict[str, tuple[str, str]] = {
    "Document": ("rag", "Document"),
    "FedRAGAnalyzer": ("rag", "FedRAGAnalyzer"),
    "build_cpi_bias_history": ("cpi_ingestion", "build_cpi_bias_history"),
    "build_dashboard_cpi_payload": ("cpi_ingestion", "build_dashboard_cpi_payload"),
    "build_cpi_knowledge_graph_payload": ("cpi_ingestion", "build_cpi_knowledge_graph_payload"),
    "BLSCPIClient": ("cpi_ingestion", "BLSCPIClient"),
    "CPISeriesDefinition": ("cpi_ingestion", "CPISeriesDefinition"),
    "CPIObservation": ("cpi_ingestion", "CPIObservation"),
    "CPIStore": ("cpi_ingestion", "CPIStore"),
    "CPIIngestionService": ("cpi_ingestion", "CPIIngestionService"),
    "CPIIngestionError": ("cpi_ingestion", "CPIIngestionError"),
    "export_dashboard_cpi_js": ("cpi_ingestion", "export_dashboard_cpi_js"),
    "export_dashboard_kg_js": ("cpi_ingestion", "export_dashboard_kg_js"),
    "build_dashboard_labor_payload": ("labor_ingestion", "build_dashboard_labor_payload"),
    "build_labor_bias_history": ("labor_ingestion", "build_labor_bias_history"),
    "build_labor_knowledge_graph_payload": ("labor_ingestion", "build_labor_knowledge_graph_payload"),
    "BLSLaborClient": ("labor_ingestion", "BLSLaborClient"),
    "LaborSeriesDefinition": ("labor_ingestion", "LaborSeriesDefinition"),
    "LaborObservation": ("labor_ingestion", "LaborObservation"),
    "LaborStore": ("labor_ingestion", "LaborStore"),
    "LaborIngestionService": ("labor_ingestion", "LaborIngestionService"),
    "LaborIngestionError": ("labor_ingestion", "LaborIngestionError"),
    "export_dashboard_labor_js": ("labor_ingestion", "export_dashboard_labor_js"),
    "export_dashboard_labor_kg_js": ("labor_ingestion", "export_dashboard_labor_kg_js"),
    "TreasuryParYieldClient": ("treasury_ingestion", "TreasuryParYieldClient"),
    "build_treasury_slope_history": ("treasury_ingestion", "build_treasury_slope_history"),
    "treasury_slope_bias": ("treasury_ingestion", "treasury_slope_bias"),
    "TreasuryPoint": ("treasury_ingestion", "TreasuryPoint"),
    "TreasuryStore": ("treasury_ingestion", "TreasuryStore"),
    "TreasuryIngestionService": ("treasury_ingestion", "TreasuryIngestionService"),
    "TreasuryIngestionError": ("treasury_ingestion", "TreasuryIngestionError"),
    "build_treasury_dashboard_payload": ("treasury_ingestion", "build_treasury_dashboard_payload"),
    "build_treasury_knowledge_graph_payload": ("treasury_ingestion", "build_treasury_knowledge_graph_payload"),
    "export_dashboard_treasury_js": ("treasury_ingestion", "export_dashboard_treasury_js"),
    "NyFedReferenceRateClient": ("policy_rates_ingestion", "NyFedReferenceRateClient"),
    "PolicyRatePoint": ("policy_rates_ingestion", "PolicyRatePoint"),
    "PolicyRateStore": ("policy_rates_ingestion", "PolicyRateStore"),
    "PolicyRateIngestionService": ("policy_rates_ingestion", "PolicyRateIngestionService"),
    "PolicyRateIngestionError": ("policy_rates_ingestion", "PolicyRateIngestionError"),
    "policy_rate_bias": ("policy_rates_ingestion", "policy_rate_bias"),
    "build_policy_rate_bias_history": ("policy_rates_ingestion", "build_policy_rate_bias_history"),
    "build_dashboard_policy_rates_payload": ("policy_rates_ingestion", "build_dashboard_policy_rates_payload"),
    "build_policy_rate_knowledge_graph_payload": (
        "policy_rates_ingestion",
        "build_policy_rate_knowledge_graph_payload",
    ),
    "export_dashboard_policy_rates_js": ("policy_rates_ingestion", "export_dashboard_policy_rates_js"),
    "TreasuryRealYieldClient": ("breakeven_ingestion", "TreasuryRealYieldClient"),
    "RealYieldPoint": ("breakeven_ingestion", "RealYieldPoint"),
    "RealYieldStore": ("breakeven_ingestion", "RealYieldStore"),
    "BreakevenIngestionService": ("breakeven_ingestion", "BreakevenIngestionService"),
    "BreakevenIngestionError": ("breakeven_ingestion", "BreakevenIngestionError"),
    "breakeven_bias": ("breakeven_ingestion", "breakeven_bias"),
    "build_breakeven_series": ("breakeven_ingestion", "build_breakeven_series"),
    "build_breakeven_bias_history": ("breakeven_ingestion", "build_breakeven_bias_history"),
    "build_dashboard_breakeven_payload": ("breakeven_ingestion", "build_dashboard_breakeven_payload"),
    "build_breakeven_knowledge_graph_payload": (
        "breakeven_ingestion",
        "build_breakeven_knowledge_graph_payload",
    ),
    "export_dashboard_breakeven_js": ("breakeven_ingestion", "export_dashboard_breakeven_js"),
    "build_dashboard_fomc_payload": ("fomc_ingestion", "build_dashboard_fomc_payload"),
    "build_dashboard_fomc_history_payload": ("fomc_ingestion", "build_dashboard_fomc_history_payload"),
    "FOMCIngestionService": ("fomc_ingestion", "FOMCIngestionService"),
    "FOMCStatement": ("fomc_ingestion", "FOMCStatement"),
    "FOMCStatementStore": ("fomc_ingestion", "FOMCStatementStore"),
    "export_dashboard_fomc_js": ("fomc_ingestion", "export_dashboard_fomc_js"),
    "export_dashboard_fomc_history_js": ("fomc_ingestion", "export_dashboard_fomc_history_js"),
    "GraphChunk": ("knowledge_graph", "GraphChunk"),
    "GraphEdge": ("knowledge_graph", "GraphEdge"),
    "GraphNode": ("knowledge_graph", "GraphNode"),
    "KnowledgeGraph": ("knowledge_graph", "KnowledgeGraph"),
    "KnowledgeGraphBuilder": ("knowledge_graph", "KnowledgeGraphBuilder"),
    "KalshiEventClient": ("market_ingestion", "KalshiEventClient"),
    "KalshiMarketClient": ("market_ingestion", "KalshiMarketClient"),
    "MarketIngestionService": ("market_ingestion", "MarketIngestionService"),
    "MarketOutcome": ("market_ingestion", "MarketOutcome"),
    "MarketSnapshot": ("market_ingestion", "MarketSnapshot"),
    "MarketSnapshotStore": ("market_ingestion", "MarketSnapshotStore"),
    "MarketWatchConfig": ("market_ingestion", "MarketWatchConfig"),
    "PolymarketEventClient": ("market_ingestion", "PolymarketEventClient"),
    "PolymarketMarketClient": ("market_ingestion", "PolymarketMarketClient"),
    "build_dashboard_market_payload": ("market_ingestion", "build_dashboard_market_payload"),
    "export_dashboard_market_js": ("market_ingestion", "export_dashboard_market_js"),
    "load_watchlist": ("market_ingestion", "load_watchlist"),
    "parse_calendar_statement_urls": ("fomc_ingestion", "parse_calendar_statement_urls"),
    "parse_statement_html": ("fomc_ingestion", "parse_statement_html"),
    "snapshot_to_document": ("market_ingestion", "snapshot_to_document"),
}


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module 'whatthefed' has no attribute {name!r}")
    module_name, attr_name = _EXPORTS[name]
    module = import_module(f".{module_name}", __name__)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
